version: "2"
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - shipping-network
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - shipping-network
    restart: unless-stopped
networks:
  shipping-network:
    driver: bridge
volumes:
  postgres:
  pgadmin: